- src/components/Cta.tsx
- src/components/MarketSubscriberForm.tsx
- src/components/Navbar.tsx
Integrates GetResponse Web Form for Newsletter Subscription.
Cta Section of Home Page
Manual user testing.
Fixes #2
> Integrate GetResponse Web Form

- src/components/Cta.tsx
Change Become a Partner to Email link
Also specified a subject and body to get started.
Checked to ensure the implementation was consistent with what was designed.
Fixes #26
> Change Become a Partner to Email link

- src/components/Cta.tsx
- src/components/MarketSubscriberForm.tsx
Change newsletter subscription from GetResponse to Mailchimp
> Change subscription to mailchimp

- src/App.tsx
- src/components/Popup.tsx
Issue {Create floating "Join our Telegram" message #9}
-added telegram popup to App
-telegram popup after 3s (3000ms)
-icon button on click closes the popup
> popup telegram

- src/components/Footer.tsx
- src/components/Navbar.tsx
@eswarasai - please merge when your completed with CI set up
> fix links to static assets

- src/App.tsx
Fixes overflow issue. `100vw` is full browser width, including any vertical scrollbar space. Therefore the site was 100% + scrollbar width. Fixing by changing to 100%.
UI
It can be easily seen that the overflow issue described in #33 is now gone.
Fixes #33
> Fix overflow issue

- package.json
- src/App.tsx
- src/containers/Team/index.tsx
- static.config.js
[SEO] Page metadata, tags and descriptions
Fixes: #60  and #57
> issue #57 #60 metadata and title

- package.json
- src/components/Navbar.tsx
This PR converts the "Whitepaper" link in the header menu to a dropdown to allow for multiple languages of the whitepaper to be linked to from the header. Right now this is needed to allow for the Chinese language whitepaper to be accessible from the header menu.
UI, Tests
https://github.com/MARKETProtocol/website/issues/46
> [NavBar] Add dropdown under white paper to allow for selection of white paper language. 

- src/components/Footer.tsx
Create more padding around text summary
UI
Yes
Fixes: #73
> Fixes: https://github.com/MARKETProtocol/website/issues/73

- src/containers/Team/config.ts
> Added bio for Robert Jordan, Fixes: #77.

- makefile
- package-lock.json
- package.json
- public/docs_sitemap.xml
- public/robots.txt
- public/sitemap.xml
- scripts/sitemap.js
Adds a sitemap.xml to help crawlers index the pages in the site.
Fixes #61
> Add sitemap

- src/components/Press/SingleLink.tsx
Adds `target="_blank"` to press links so they get opened in a new tab.
UX
Manual testing
> Open press links in a new tab

- .travis.yml
> Added travis script for build

- src/containers/Press/config.tsx
- Add Seth Rubin's Coincrunch podcast to the press page
- Moves 'Top 4 Upcoming Cryptocurrencies Sans ICOs' article from The Merkle to the 3rd item to avoid displaying the two articles from The Merkle next to each other.
UI
Yeah, I did.
Fixes https://github.com/MARKETProtocol/website/issues/95
> Add Seth Rubin's Coincrunch podcast to the press page

- src/breakpoints.tsx
- src/components/Navbar.tsx
- Adds about link to header 
- Fixes responsiveness issues in breakpoints 768px - 991px
- Removes Telegram link from the header
I 
Fixes #101
> Add about link to header and fix responsiveness issues

- src/Styles.tsx
- src/components/About/Banner.tsx
- src/components/About/Derivatives.tsx
- src/components/About/Opensource.tsx
- src/components/About/Timeline.tsx
- src/components/About/Trading.tsx
- src/components/BuildDapp.tsx
- src/components/Chain.tsx
- src/components/Cta.tsx
- src/components/Dapp.tsx
- src/components/Hero.tsx
- src/components/Solution.tsx
- src/containers/404.tsx
- src/containers/About.tsx
- src/containers/Partners/index.tsx
- src/containers/Press/index.tsx
- src/containers/Team/index.tsx
- static.config.js
- test/components/BuildDapp.test.tsx
- test/components/Chain.test.tsx
- test/components/Cta.test.tsx
- test/components/Dapp.test.tsx
- test/components/Solution.test.tsx
- test/containers/404.test.tsx
- test/containers/Partners/Partners.test.tsx
- test/containers/Press/Press.test.tsx
- test/containers/Team/Team.test.tsx
- Updates the main headline in the home page to be bold
- Updates the font weight of titles to be semi-bold
- Create a new `MarketHeader` component
- Update `MarketText` component to use `div` instead of `h1`
- Make changes throughout the app to accommodate the above-mentioned changes.
UI
I did test it.
Fixes #102
> Improve typography throughout the app

- src/containers/Press/index.tsx
Reduces the JS bundle size by modularly importing `throttle` function from `lodash`
Fixes #134
> Modularly import throttle function

- src/components/Navbar.tsx
- src/components/Popup.tsx
- src/containers/About.tsx
- src/containers/Press/index.tsx
- src/containers/Team/index.tsx
- test/components/BuildDapp.test.tsx
- test/components/MarketSubscriberForm.test.tsx
- test/components/Navbar.test.tsx
- test/containers/GoogleAnalyticsTracker.test.tsx
Removes unused imports and variables throughout the codebase
> Remove unused imports and variables

- src/containers/Press/config.tsx
Adds Bluzelle partnership press coverage on CryptoNinjas to the press page
Fixes #177
> Add Bluzelle partnership press coverage on CryptoNinjas

- package-lock.json
- package.json
- src/components/Blog/PostPreview.tsx
- src/containers/Blog/Blog.tsx
- test/containers/Blog/Blog.test.tsx
We want users to be able to load more awesome posts!
UI, UX, Tests
Fixes: #184
> Add loading of more posts

- src/components/About/Hero.tsx
- src/components/Hero.tsx
- src/components/Navbar.tsx
- src/components/Partners/Hero.tsx
- src/components/Team/Hero.tsx
There are multiple issues with the website on chrome on iOS. 
UI, UX
Remove hero image mobile
Fixes: #193
> MISC mobile site fixes

- public/admin/config.yml
- src/components/Blog/VerticalPostPreview.tsx
- src/containers/Blog/Blog.tsx
- src/containers/BlogPost/BlogPost.tsx
- test/components/Blog/PostPreview.test.tsx
- test/components/Blog/VerticalPostPreview.test.tsx
- test/containers/Blog/Blog.test.tsx
- test/containers/BlogPost/BlogPost.test.tsx
This PR removes future medium link usage on the blog.
Code
Refers: #207
> Remove medium link from blog

- src/containers/Partners/config.ts
Updated the Amadeus Partner URL to the correct one.
- Partners Page/Container
> Fix: Correct Amadeus Partner URL

- src/Styles.tsx
- src/components/Cta.tsx
- src/components/Hero.tsx
Added 'Watch Video' CTA button in homepage hero section 
UI
Fixes: #231
> Added explainer video CTA in homepage hero section

- src/components/ExplainerCta.tsx
- src/containers/Home.tsx
- src/containers/HomeRouteWrapper.tsx
- src/containers/Video.tsx
- static.config.js
- test/containers/Home.test.tsx
1. Added new route to `static.config.js`
2. Created a route wrapper passing the routeData to HomeComponent
3. Added test case for video expansion on "./video" route navigation
UI/UX
Video Section on "./video" route
1. Navigate to Home Page and modify the url to "./video" and see that video is expanded and played.
2. Navigate to other sections to enforce it doesn't after other views.
3. Run test cases
Fixes: #242
> Adding Route to Video Section

- src/components/Cta.tsx
- src/containers/Home.tsx
- src/containers/Subscribe.tsx
- static.config.js
- test/Cta.test.tsx
- test/containers/Home.test.tsx
- test/containers/Subscribe.test.tsx
Adds a new Subscribe page
I've added a basic test to make sure my code works and all other tests pass.
Fixes #244
> Add Subscribe page

- package-lock.json
- package.json
- src/Styles.tsx
- src/components/MarketSubscriberForm.tsx
- src/components/TokenInterest/TokenInterestForm.tsx
- src/constants/environment.ts
- test/components/MarketSubscriberForm.test.tsx
- test/components/TokenInterest/TokenInterestForm.test.tsx
Solves #255 by changing the web subscription forms to point at the mail-lister service API.
UI, Tests
The change has been tested manually and all form tests have been updated.
Fixes: #255
> Alter marketing forms to use mail-lister service API
